name: acesso remoto
on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      version:
        description: 'Qual a versão?'
        required: false

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Executando comandos por SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          echo .
          echo .
          echo .
          echo COMEÇANDO DEPLOY
          echo .
          echo .
          ls
          echo .
          echo .
          cd teste-nodejs
          echo .
          echo .
          git pull
          echo .
          echo .
          npm install
          echo .
          echo .
          pm2 restart all
          echo .
          echo .